### ISSUE TITLE
Need to filter out dummy albums.

### ISSUE THREAD

**Issue by vvasuki** [Jagalite/Save-to-Google-Photos#2]
I see dummy albums such as the below (perhaps they come from "sharing" photos with Google photos web ui?):
![image](https://cloud.githubusercontent.com/assets/2664797/26279430/85f1843e-3d68-11e7-95d0-7396d045262e.png)

These don't exist if I go to https://photos.google.com/albums . It would be nice to filter them out..

**Comment by vvasuki** [comment]
Also I wonder what the 1% Full means..

**Comment by Jagalite** [comment]
delete more albums here: https://picasaweb.google.com/home?showall=true

Also, google photos impose a 2000 photo album limit, so when it is full(100%) you won't be able to save anymore to that album.

**Comment by vvasuki** [comment]
> delete more albums here: https://picasaweb.google.com/home?showall=true

You mean that you want the user to go to picasaweb (which is on its way out, if not already deprecated) and delete their albums, thereby causing problems with shared pics? A better fix is to have the extension ignore such albums..

**Comment by Jagalite** [comment]
Well, I found that these albums are primarily created by android and its photos app.

It does make sense that this extension should match with the albums you see at photo.google.com.

Let me try to ignore albums like this.

**Comment by Jagalite** [comment]
version 8.3 solves this issue. Should correctly match photo.google.com
