### ISSUE TITLE
it doesn't work in recent days

### ISSUE THREAD

**Issue by Wyvern** [Jagalite/Save-to-Google-Photos#5]
this useful extension not work normally in recent two days, please fix it asap.

**Comment by Jagalite** [comment]
What exactly doesn't work? Saving an image or loading all the albums?

**Comment by Wyvern** [comment]
Saving images report error
<img width="39" alt="screen shot 2018-05-21 at 4 34 59 pm" src="https://user-images.githubusercontent.com/32942/40298280-338eb63a-5d15-11e8-86bf-8172228c5c85.png">

**Comment by Wyvern** [comment]
back to working normally about only one day, now it's broken again...
show "save" badge but nothing stored to google photos
<img width="29" alt="screen shot 2018-05-25 at 3 34 47 am" src="https://user-images.githubusercontent.com/32942/40509697-e0df1884-5fcc-11e8-903c-5e10191c139d.png">

**Comment by Jagalite** [comment]
please try again

**Comment by Wyvern** [comment]
well done~ it works normally, thanks a lot!

**Comment by Jagalite** [comment]
an error might pop up again, but everything should be fine after the first time authentication. Try to save again.

**Comment by Wyvern** [comment]
tried several times, still report error and nothing saved to GPhotos 😞

**Comment by Jagalite** [comment]
have you tried reinstalling the extension after the fix...or logging out of the browser? maybe try another account? Try saving this image: https://3c1703fe8d.site.internapcdn.net/newman/gfx/news/hires/2017/docatspurrwh.jpg

**Comment by Wyvern** [comment]
thanks for your help, clearing cookies and site data after reinstalling the extension, the problem has gone. works normally for now~

**Comment by Wyvern** [comment]
now it's broken AGAIN, report ERROR no image stored.........

**Comment by Wyvern** [comment]
now it's broken AGAIN, report ERROR no image stored.........

**Comment by Jagalite** [comment]
Ahh ok! Thanks for bringing this to my attention.

**Comment by Wyvern** [comment]
most of  ERRORs occurred during save facebook photos, like http://scontent-icn1-1.xx.fbcdn.net/.... would generate a very long address length; maybe this help you 
 to fix the problem

**Comment by Jagalite** [comment]
I have shorten the URL. A fix has been submitted, you should be getting it soon.

**Comment by Wyvern** [comment]
thanks for your fix, already updated to latest 9.0 version but the ERROR still exists, same report same error code...
<img width="696" alt="screen shot 2018-06-02 at 8 11 50 pm" src="https://user-images.githubusercontent.com/32942/40874422-a4b47436-66a1-11e8-83e2-3da3b2b5ffcc.png">
<img width="510" alt="screen shot 2018-06-02 at 8 13 56 pm" src="https://user-images.githubusercontent.com/32942/40874423-a4f55e24-66a1-11e8-96da-03d4b35a7a54.png">

**Comment by Jagalite** [comment]
I will trim it down once again to at least 256. Pushing the update out now.

**Comment by Wyvern** [comment]
Thanks for your quick response and fix. 9.1 version works normally without error, so far so good. ~
